Combine two `jq` invocations into one
Also choose a nicer file name for the original file since we now archive it too.

diff --git a/.github/workflows/jenkins-security-scan.yaml b/.github/workflows/jenkins-security-scan.yaml
--- a/.github/workflows/jenkins-security-scan.yaml
+++ b/.github/workflows/jenkins-security-scan.yaml
@@ -63,18 +63,18 @@ jobs:
           echo "::endgroup::"
 
           echo "::group::Analyze Database"
-          codeql database analyze --sarif-add-query-help --format=sarifv2.1.0 --output=output.sarif "$GITHUB_WORKSPACE/database" "$CODEQL_RULES_DIR/src/" codeql/java-queries:AlertSuppression.ql codeql/java-queries:AlertSuppressionAnnotations.ql || { echo "Failed to analyze database" >&2 ; exit 1 ; }
+          codeql database analyze --sarif-add-query-help --format=sarifv2.1.0 --output=jenkins-security-scan-raw.sarif "$GITHUB_WORKSPACE/database" "$CODEQL_RULES_DIR/src/" codeql/java-queries:AlertSuppression.ql codeql/java-queries:AlertSuppressionAnnotations.ql || { echo "Failed to analyze database" >&2 ; exit 1 ; }
           echo "::endgroup::"
 
-          # Manually remove suppressed warnings because GitHub Code Scanning does not support inline suppressions
-          jq 'del(.runs[].results[] | select( .suppressions | length != 0 ))' output.sarif > output-without-suppressed.sarif
-          # Prevent conflicts with otherwise set up CodeQL scan
-          jq 'setpath(path(.runs[].tool.driver.name); "Jenkins Security Scan") | setpath(path(.runs[].tool.driver.organization); "Jenkins Project")' output-without-suppressed.sarif > jenkins-security-scan.sarif
+          # Process the generated SARIF file:
+          # 1. Prevent conflicts with otherwise set up CodeQL scan by renaming the tool driver
+          # 2. Remove suppressed warnings because GitHub Code Scanning does not support inline suppressions
+          jq 'setpath(path(.runs[].tool.driver.name); "Jenkins Security Scan") | setpath(path(.runs[].tool.driver.organization); "Jenkins Project") | del(.runs[].results[] | select( .suppressions | length != 0 ))' jenkins-security-scan-raw.sarif > jenkins-security-scan.sarif
       - name: Archive SARIF
         uses: actions/upload-artifact@v3
         with:
           path: |
-            output.sarif
+            jenkins-security-scan-raw.sarif
             jenkins-security-scan.sarif
           name: Jenkins Security Scan SARIF
       - name: Upload Scan Result
